name: Setup

description: Setup Node.js, cache and install dependencies

runs:
  using: composite
  steps:
    - uses: sharathck087/sqlserver-github-action@v1
      with:
        node-version: "18"
        cache: "yarn"

    - name: start sql server tools
      shell: bash
      run: yarn install --immutable
                    
            
