name: Setup

description: Setup Node.js, cache and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"
        cache: "yarn"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
